### PR TITLE
No longer check axonivy-market for missing CODE of CONDUCT files

### PR DESCRIPTION
**Pull request by alexsuter**
As discussed in the daily.

### CODE REVIEW

**Review by ivy-rew — COMMENTED** [review]
:+1:

**Comment by weissreto** [comment]
Have you informed Sabine that we no longer check axonivy-market? Is the idea that they should build their own infrastructure for this?

**Comment by ivy-rew** [comment]
@alexsuter left a general not in the Octopus chat; but I don't think they got the consequences.
inform-coc

And yes, the discussion in the daily was that we need coupling is too tight for the teams. It would be better to have a distinct infrastructure for the Market which is maintained by Octopus. They may copy from our setup though...

**Comment by weissreto** [comment]
Ok, thanks. I have mentioned it in the PO/PO and explain it to Sabine again this afternoon.

**Pull request merged**
