### PR TITLE
Update raise version job to node 18

### PR DESCRIPTION
**Pull request by ivy-lli**

### CODE REVIEW

**Review by ivy-cst — COMMENTED** [review]
Does this work also for old branches? We need may be another concept here in the future ...

**Comment by ivy-lli** [comment]
I will try... But you're right, it will may fail in the future.

**Comment by ivy-lli** [comment]
Yes currently it works like this 👍

**Comment by ivy-cst** [comment]
Perfect thanks. I think in general what we do does not or should not depend on the node version :+1:

**Pull request merged**
