### PR TITLE
Use environment variable for github token file

### PR DESCRIPTION
**Pull request by ivy-cst**
Use the environment variable 'GITHUB_TOKEN_FILE'
If env variable GITHUB_TOKEN_FILE is not set:
- Only check if github cli is authenticated
- This is usefull if used localy where the gh cli is authenticated anyway

### CODE REVIEW

**Comment by ivy-cst** [comment]
See how it works: https://jenkins.ivyteam.io/job/github-repo-manager_raise-deps/job/use-env-for-github-token-for-raise-scripts/2/

**Review by ivy-lli — APPROVED** [review]
🆒

**Review by alexsuter — APPROVED** [review]
LGTM. I've lost the overview over all changes. 

You may fix README.md

**Comment by ivy-cst** [comment]
> LGTM. I've lost the overview over all changes.
> 
> You may fix README.md

The README.md does not cover the raise use cases, but true I should enhance it!
Because not it is also easy possible to run the raise scripts locally if needed.

**Pull request merged**
